config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'

  resource :home
  resources :requests
  resources :responses

  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/node.rb
class Node < ApplicationRecord
  has_closure_tree

  belongs_to :user

  enum status: [:open]
end

app/models/request.rb
class Request < Node
  has_many :responses, foreign_key: 'parent_id'

  enum status: superclass.statuses.keys + %w(accepted)

  accepts_nested_attributes_for :responses, reject_if: :response_has_mail?

  def response_has_mail?(attributes)
    attributes['email'].blank?
  end
end

app/models/response.rb
class Response < Node
  before_validation :owner_from_email
  after_validation :update_status
  attr_accessor :email

  belongs_to :user
  has_many :responses, foreign_key: 'parent_id'

  enum status: superclass.statuses.keys + %w(edited
                                             answered delegated
                                             answered_and_delegated
                                             accepted)

  accepts_nested_attributes_for :responses, reject_if: :response_has_mail?

  validates :description, presence: true,
                          if: :no_respondents?,
                          unless: :open?

  validates :responses, length: { minimum: 1 },
                        if: :no_description?,
                        unless: :open?

  def owner_from_email
    self.user = User.find_by_email @email unless @email.nil?
  end

  def update_status
    if respondents? && description?
      self.status = :answered_and_delegated
    elsif respondents?
      self.status = :delegated
    elsif description?
      self.status = :answered
    end
  end

  def respondents?
    !responses.empty?
  end

  def no_respondents?
    responses.empty?
  end

  def no_description?
    !description?
  end

  def response_has_mail?(attributes)
    attributes['email'].blank?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :requests
  has_many :responses, inverse_of: :user

  def build_request(num_responses: 2)
    request = requests.build
    num_responses.times { request.responses.build }
    request
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :authenticate_user!

  def new
    @request = current_user.build_request(num_responses: 2)
  end

  def index
    @requests = current_user.requests
  end

  def show
    # TODO: make sure the user is allowed to read this, i.e.
    # check if one of the responses of the user has a root
    # with the given id
    @request = Request.find_by_id params[:id]
  end

  def create
    @request = current_user.requests.build(request_params)
    if @request.save
      redirect_to @request, notice: 'Request successfully created'
    else
      render :new
    end
  end

  def request_params
    responses_attributes = {
      responses_attributes: [:id, :email, :_destroy]
    }

    params.require(:request).permit(:description, responses_attributes)
  end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  before_action :authenticate_user!

  def index
    @responses = current_user.responses
  end

  def show
    @response = current_user.responses.find_by_id params[:id]
  end

  def update
    @response = current_user.responses.find_by_id(params[:id])
    @response.update_attributes(response_params.merge(status: :edited))

    if @response.save
      redirect_to @response, notice: 'Response successfully created'
    else
      alert_message = 'Please answer the question or delegate it.'
      flash.now[:alert] = alert_message
      render 'show'
    end
  end

  def response_params
    response_attributes = {
      responses_attributes: [:id, :email, :_destroy]
    }

    params.require(:response).permit(:description, :status,
                                     response_attributes)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(link_path)
    current_page?(link_path) ? 'active' : ''
  end

  def nav_link(name, link_path, opts = {})
    content_tag :li, class: "nav-item #{active_class(link_path)}" do
      link_to name, link_path, opts.merge(class: 'nav-link')
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
  def status_for(request)
    "fa fa-#{icon_name_for_status request.status}"
  end

  def icon_name_for_status(status)
    case status
    when 'open'
      'question-circle'
    when 'delegated'
      'share'
    when 'answered'
      'commenting'
    when 'accepted'
      'check'
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Treeofanswers</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-light bg-faded">
      <a class="navbar-brand" href="#">Tree of Answers</a>
      <ul class="nav navbar-nav">
        <%= nav_link 'Home', root_path %>
        <%= nav_link 'New request', new_request_path %>
        <%= nav_link 'Requests', requests_path %>
        <%= nav_link 'Responses', responses_path %>
      </ul>

      <ul class="nav navbar-nav pull-xs-right">
        <% if user_signed_in? %>
          <li class='nav-item'>
            <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
        <% else %>
          <%= nav_link 'Sign up', new_user_registration_path %>
          <%= nav_link 'Log in', new_user_session_path %>
        <% end %>

      </ul>
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/requests/_response_fields.html.erb
<div class="nested-fields response" id="response-<%= f.index %>">
  <%= f.inputs do %>
    <%= f.input :email, as: :email %>

    <%= link_to_remove_association 'Remove', f %>
  <% end %>
</div>

app/views/requests/index.html.erb
<ul class="requests">

</ul>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Status</th>
      <th>Description</th>
      <th>Participants</th>
    </tr>
  </thead>
  <tbody>
    <% @requests.each_with_index do |request, index| %>
      <tr id="request-#{index}">
        <td>
          Status
        </td>
        <td>
          <%= link_to truncate(request.description), request_path(request) %>
        </td>
        <td>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/requests/new.html.erb
Foo?
<%= semantic_form_for @request do |f| %>
  <% f.inputs %>
    <%= f.input :description, input_html: { class: 'autogrow', rows: 5, cols: 20 } %>
<h3>Responses</h3>
  <div id="responses">
    <%= f.semantic_fields_for :responses do |response| %>
      <%= render 'response_fields', f: response %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'Add respondent', f, :responses %>
    </div>
    <%= f.actions do %>
      <%= f.actions :submit %>
    <% end %>
  </div>
<% end %>

app/views/requests/show.html.erb
<div id="request" data-id="<%= @request.id %>">
    <div class="col-sm-4">
      <div id="request-tree"></div>
    </div>
    <div class="col-sm-8">
      <h2>Request</h2>
      <div class="description">
        <blockquote class="blockquote">
          <%= @request.description %>
        </blockquote>
      </div>
      <h2>Response</h2>
      <div class="response" id="response">

      </div>
    </div>
  </div>
</div>

app/views/responses/_response_fields.html.erb
<div class="nested-fields response">
  <%= f.inputs do %>
    <%= f.input :email, as: :email %>

    <%= link_to_remove_association 'Remove', f %>
  <% end %>
</div>

app/views/responses/index.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>Status</th>
      <th>Description</th>
      <th>Participants</th>
    </tr>
  </thead>
  <tbody>
    <% @responses.each_with_index do |response, index| %>
      <tr id="response-#{index}">
        <td>
          Status
        </td>
        <td>
          <%= link_to truncate(response.root.description), response_path(response) %>
        </td>
        <td>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/responses/show.html.erb
<div id="request" data-id="<%= @response.root.id %>">
    <div class="col-sm-4">
      <div id="request-tree"></div>
    </div>
    <div class="col-sm-8">
      <h2>Request</h2>
      <div class="description">
        <blockquote class="blockquote">
          <%= @response.root.description %>
        </blockquote>
      </div>
      <h2>Response</h2>
      <div class="response" id="response">
      </div>
      <h2>User response</h2>
      <div class="response" id="user-response">
        <%= semantic_form_for @response do |f| %>
          <% f.inputs %>
            <%= f.input :description, input_html: { class: 'autogrow', rows: 5, cols: 20 } %>
            <h3>Delegated to</h3>
            <ul>
              <% @response.responses.each do |r| %>
                <li><%= r.user.email %></li>
              <% end %>
            </ul>
            <div class="links">
              <%= link_to_add_association 'Add respondent', f, :responses %>
            </div>
            <%= f.actions do %>
              <%= f.actions :submit %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>